const {test,expect}=require('@playwright/test');const fs=require('fs');
const engine=()=>import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync('app/holeCaddie.js','utf8')+'\n'+fs.readFileSync('app/fieldValidation.js','utf8').replace(/^import .*;\n/,'')).toString('base64'));
test('distance comparison uses error and GPS quality without claiming field signoff',async()=>{
 const m=await engine(),now=Date.now(),a={lat:35.664,lng:128.648,accuracy:5,at:new Date(now).toISOString(),fixAt:new Date(now).toISOString()},b={...a,lat:35.665},d=m.meters(a,b);
 expect(m.assessFieldDistance({a,b,reference:d,now}).status).toBe('WITHIN_TOLERANCE');expect(m.assessFieldDistance({a,b,reference:d+7,now}).status).toBe('OUTSIDE_TOLERANCE');expect(m.assessFieldDistance({a:{...a,accuracy:50},b,reference:d,now}).status).toBe('GPS_QUALITY_REVIEW');expect(m.assessFieldDistance({a:{...a,at:new Date(now-90000000).toISOString()},b,reference:d,now}).status).toBe('GPS_QUALITY_REVIEW');expect(m.assessFieldDistance({a:{...a,fixAt:new Date(now-120000).toISOString()},b,reference:d,now}).status).toBe('GPS_QUALITY_REVIEW');expect(m.assessFieldDistance({a:{...a,fixAt:null},b,reference:d,now}).status).toBe('GPS_QUALITY_REVIEW');expect(m.assessFieldDistance({a,b,reference:0,now}).status).toBe('MISSING');expect(m.assessFieldDistance({a,b,reference:1600,now}).status).toBe('MISSING');
});
test('field comparison records reload, duplicate prevention and scope by hole',async({page})=>{
 await page.addInitScript(()=>{const a={lat:35.664,lng:128.648,accuracy:5,at:new Date().toISOString(),fixAt:new Date().toISOString()},b={...a,lat:35.665};if(!localStorage.getItem('fixtureReady')){localStorage.setItem('golfTarget:grace-cc:Lake:1:points',JSON.stringify({a,b}));localStorage.setItem('fixtureReady','1');}});await page.goto('/');await page.getByRole('button',{name:'거리 측정',exact:true}).first().click();const cmp=page.getByLabel('GPS 실측 거리 비교').first();await cmp.getByLabel('실측 기준 거리').fill('111.2');await expect(cmp.getByRole('status')).toContainText('이 비교 기록의 기준 충족');await cmp.getByRole('button',{name:'거리 비교 기록 저장',exact:true}).click();await expect(cmp.getByText('거리 비교 기록 1건')).toBeVisible();await cmp.getByRole('button',{name:'거리 비교 기록 저장',exact:true}).click();await expect(cmp.getByRole('status')).toContainText('이미 기록했습니다');await page.reload();await page.getByRole('button',{name:'거리 측정',exact:true}).first().click();await expect(cmp.getByText('거리 비교 기록 1건')).toBeVisible();
 await page.locator('.stripHoles').first().getByRole('button',{name:'2',exact:true}).click();await expect(cmp.getByText('거리 비교 기록 0건')).toBeVisible();await expect(cmp.getByRole('button',{name:'거리 비교 기록 저장',exact:true})).toBeDisabled();
});
test('corrupted package is retained for recovery and never crashes caddie or DB',async({page})=>{
 const raw=JSON.stringify({type:'GolfCoursePackage',schemaVersion:1,courseId:'grace-cc',holes:'broken'});await page.addInitScript(raw=>localStorage.setItem('golfCoursePackage:grace-cc',raw),raw);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByLabel('LAKE 1H 개별 홀 공략도')).toBeVisible();await page.locator('.nav').getByRole('button',{name:'골프장 DB',exact:true}).click();await expect(page.getByRole('status')).toContainText('저장된 홀 자료를 읽을 수 없습니다');expect(await page.evaluate(()=>localStorage.getItem('golfCoursePackage:grace-cc'))).toBe(raw);expect(errors).toEqual([]);
});
