'use client';
import {useEffect,useState} from 'react';
import {assessFieldDistance,fieldSampleKey} from './fieldValidation';
export default function FieldValidation({storageKey,a,b}){
 const [reference,setReference]=useState(''),[source,setSource]=useState('레이저 거리계'),[records,setRecords]=useState([]),[message,setMessage]=useState('');
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem(storageKey)||'[]');setRecords(Array.isArray(p)?p.filter(r=>r&&typeof r.sampleKey==='string'&&Number.isFinite(r.error)&&Number.isFinite(r.gpsDistance)&&Number.isFinite(r.reference)&&typeof r.at==='string').slice(-100):[]);}catch{setRecords([]);}setReference('');setMessage('');},[storageKey]);
 const result=assessFieldDistance({a,b,reference});
 const save=()=>{const check=assessFieldDistance({a,b,reference});if(check.status==='MISSING')return;const sampleKey=fieldSampleKey(a,b);if(records.some(r=>r.sampleKey===sampleKey)){setMessage('같은 A·B 측정은 이미 기록했습니다. 위치를 다시 측정한 뒤 비교하세요.');return;}const next=[...records,{...check,a,b,source,sampleKey,at:new Date().toISOString()}].slice(-100);try{localStorage.setItem(storageKey,JSON.stringify(next));setRecords(next);setMessage('거리 비교 기록 저장 완료');}catch{setMessage('저장 공간이 부족하거나 저장이 차단되어 기록하지 못했습니다. 기존 기록은 유지했습니다.');}};
 return <section aria-label="GPS 실측 거리 비교"><h4>GPS 실측 거리 비교</h4><p>같은 두 지점 사이의 GPS 거리와 거리계·실측 거리를 비교하세요.</p><div className="inline"><label>기준 거리(m)<input aria-label="실측 기준 거리" type="number" min="1" max="1500" step="0.1" value={reference} onChange={e=>setReference(e.target.value)}/></label><label>측정 방식<select aria-label="실측 기준 방식" value={source} onChange={e=>setSource(e.target.value)}><option>레이저 거리계</option><option>줄자·실측</option></select></label></div><p>A GPS ±{a?.accuracy??'-'}m · B GPS ±{b?.accuracy??'-'}m</p>{result.status!=='MISSING'&&<p>GPS {result.gpsDistance.toFixed(1)}m · 기준 {result.reference}m · 차이 {result.error>0?'+':''}{result.error.toFixed(1)}m</p>}<p role="status">{message||result.message}</p><button type="button" disabled={result.status==='MISSING'} onClick={save}>거리 비교 기록 저장</button><small>앱 비교 기준: 차이 5m 이내, 당일 자료, 저장 전 1분 이내 GPS 수신, GPS 제공 정확도 각각 10m 이내. 이 기록만으로 홀 전체나 P0 검증이 완료되지는 않습니다. 기기에 저장됩니다.</small><details><summary>거리 비교 기록 {records.length}건</summary>{records.map(r=><p key={r.sampleKey}>{r.at.slice(0,10)} · {r.source} · GPS {r.gpsDistance.toFixed(1)}m / 기준 {r.reference}m · 차이 {r.error.toFixed(1)}m · {r.status==='WITHIN_TOLERANCE'?'비교 기준 충족':'재확인 필요'}</p>)}</details></section>;
}
