"use client";
import {useEffect,useRef,useState} from 'react';
import {GRACE_REFERENCE_SOURCES} from '../data/courseReferences';
export default function HoleArtwork({hole,courseName,storageKey,onSatellite}){
 const [image,setImage]=useState(''),[draft,setDraft]=useState(''),[error,setError]=useState('');
 const latestRead=useRef(0),fileRef=useRef(null);
 useEffect(()=>{try{const value=localStorage.getItem(storageKey+':artwork');if(value?.startsWith('data:image/'))setImage(value);}catch{}return()=>{latestRead.current++;};},[storageKey]);
 async function readFile(e){const file=e.target.files?.[0],id=++latestRead.current;e.target.value='';setDraft('');setError('');if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024){setError('PNG·JPG·WebP 사진을 2MB 이하로 선택해 주세요.');return;}const reader=new FileReader();reader.onload=()=>{if(id===latestRead.current)setDraft(String(reader.result));};reader.onerror=()=>setError('사진을 읽지 못했습니다.');reader.readAsDataURL(file);}
 function save(){try{localStorage.setItem(storageKey+':artwork',draft);setImage(draft);setDraft('');}catch{setError('사진을 저장할 공간이 부족합니다. 사진 크기를 줄여 주세요.');}}
 return <section className="fieldCaddie holeArtwork" aria-label="개별 홀 지도 자료 대기"><h3>{courseName.toUpperCase()} {hole.hole}H · Par {hole.par} · {hole.distance}m</h3>{draft||image?<><img src={draft||image} alt={`${courseName} ${hole.hole}홀 사용자 등록 공략도`}/><small>사용자 등록 홀 사진 · GPS 좌표와 별도</small></>:<div className="holeArtworkMissing"><span aria-hidden="true">▧</span><p>이 홀의 개별 공략도와 좌표 자료를 준비 중입니다.</p><p>다른 홀의 그림을 대신 표시하지 않습니다.</p><b>{hole.title}</b><p>{hole.strategy}</p></div>}{storageKey.includes('grace-cc')&&<aside className="holeReferenceSources" aria-label={`${courseName} ${hole.hole}홀 공개 참고자료`}><h4>이 홀 참고자료</h4><a href={GRACE_REFERENCE_SOURCES.find(s=>s.id==='field-photos').url} target="_blank" rel="noopener noreferrer">{courseName.toUpperCase()} {hole.hole}홀 현장사진 원문 보기 ↗</a><small>2019년 사진 · 원문에서 {courseName==='Mountain'?hole.hole+9:hole.hole}번 홀 확인. 현재 지형·거리와 다를 수 있습니다.</small><a href={GRACE_REFERENCE_SOURCES.find(s=>s.id==='course-summary-2026').url} target="_blank" rel="noopener noreferrer">27홀 코스 소개 보기 ↗</a><small>외부 참고자료이며 GPS 좌표가 등록되는 것은 아닙니다.</small></aside>}<div className="holeArtworkActions"><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" aria-label={`${courseName} ${hole.hole}홀 공략도 사진`} onChange={readFile}/><button onClick={()=>fileRef.current?.click()}>{image?'공략도 사진 수정':'이 홀 공략도 사진 등록'}</button>{draft&&<><button onClick={save}>사진 저장 &amp; 반영</button><button onClick={()=>{latestRead.current++;setDraft('');}}>취소</button></>}<button onClick={onSatellite}>실제 위성·GPS 열기</button></div>{error&&<p role="alert">{error}</p>}</section>;
}
